import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy — LifePilot",
};

export default function PrivacyPage() {
  return (
    <div className="mx-auto max-w-2xl px-4 py-12 space-y-8 text-sm leading-relaxed">
      <div className="space-y-1">
        <h1 className="text-2xl font-semibold">Privacy Policy</h1>
        <p className="text-muted-foreground">Last updated: June 2026</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">1. What we collect</h2>
        <p>
          LifePilot collects the information you provide during onboarding (name, age, location,
          financial context), your daily check-in responses, goal definitions, and AI-generated
          briefings. We also collect standard authentication data (email address, hashed password)
          via Supabase.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">2. Legal basis (GDPR)</h2>
        <p>
          Processing is based on <strong>contract performance</strong> (GDPR Art. 6(1)(b)) — we
          need your data to deliver personalised daily coaching. Where consent is separately
          required (marketing emails), it is collected explicitly and can be withdrawn at any time
          from your settings.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">3. How we use your data</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>Generate your personalised daily briefing via Anthropic Claude (AI)</li>
          <li>Track progress toward your goals</li>
          <li>Send you briefings and (if opted in) re-engagement emails via Resend</li>
          <li>Detect inactivity and prompt re-engagement</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">4. Sub-processors</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li><strong>Supabase</strong> — database and authentication (EU region)</li>
          <li><strong>Anthropic</strong> — AI content generation (check-in data sent for briefing)</li>
          <li><strong>Resend</strong> — transactional email delivery</li>
          <li><strong>Vercel</strong> — hosting and serverless compute</li>
          <li><strong>Inngest</strong> — background job orchestration</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">5. Retention</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>Check-in data: deleted after 12 months</li>
          <li>Briefings: deleted after 6 months</li>
          <li>Account data: deleted within 30 days of account deletion</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">6. Your rights</h2>
        <p>
          Under GDPR you have the right to access, rectify, erase, restrict, and port your data.
          You can export a copy of all your data or permanently delete your account from the{" "}
          <Link href="/data" className="text-primary underline-offset-4 hover:underline">
            Data &amp; Privacy
          </Link>{" "}
          page. For other requests, contact us at{" "}
          <a href="mailto:privacy@lifepilot.app" className="text-primary underline-offset-4 hover:underline">
            privacy@lifepilot.app
          </a>
          .
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">7. AI-generated content (EU AI Act 2024)</h2>
        <p>
          Briefings are generated by an AI system. All AI-generated content is clearly labelled
          within the app. LifePilot does not use your data to train AI models.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-base font-semibold">8. Cookies</h2>
        <p>
          We use a single session cookie issued by Supabase for authentication. No third-party
          advertising or analytics cookies are set.
        </p>
      </section>

      <p className="text-muted-foreground pt-4 border-t border-border">
        Questions?{" "}
        <a href="mailto:privacy@lifepilot.app" className="text-primary underline-offset-4 hover:underline">
          privacy@lifepilot.app
        </a>
      </p>
    </div>
  );
}
